# syntax=docker/dockerfile:1
FROM python:<%= @env[:base][:python_version][:value] %>
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
