# syntax=docker/dockerfile:1

FROM python:<%= @env[:base][:python_version][:value] %> AS builder
WORKDIR /code

RUN python -m pip install Django
RUN python -m pip install psycopg2
RUN django-admin startproject <%= @env[:base][:app_name][:value] %> .

COPY . /code/

RUN pip freeze > requirements.txt

FROM scratch AS export-stage

COPY --from=builder ./code/ .