include:
  - docker-compose.builders.yml  

services:

  development: &development 
    extends:
      file: docker-compose.builders.yml
      service: roro-development
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
      - gem_cache:/usr/local/bundle/gems

  dev: 
    <<: *development

  test: &test
    <<: *development
    container_name: test

  guard:
    <<: *test
    command: bundle exec guard
    container_name: guard

  production: &production
    extends:
      file: docker-compose.builders.yml
      service: roro-production
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
      - gem_cache:/usr/local/bundle/gems

  roro:
    <<: *production
    volumes:
      - .:/artifact
    image: handsomefencer/roro
    command: ['sh']

volumes:
  gem_cache:  