
services:

  development: &development
    build:
      dockerfile: ./mise/containers/unstoppable/Dockerfile
      target: unstoppable
    image: unstoppable/development
    volumes:
      - .:/usr/src/unstoppable
      - /var/run/docker.sock:/var/run/docker.sock
      - gem_cache:/usr/local/bundle/gems
 

  # base:
  #   build:
  #     <<: *build
  #     target: base
  #   image: roro/base

  # dev: &development
  #   build:
  #     <<: *build
  #     target: development
  #   container_name: development
  #   image: roro/development
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ../roro:/usr/src/roro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - gem_cache:/usr/local/bundle/gems
  test: &test
    <<: *development
    command: bundle exec guard
    container_name: test

  # ci: 
  #   <<: *test
  #   command: "bundle exec rake test:roro:stacks:ci"
  #   environment: 
  #     CI: "true"
  #     CIRCLE_TEST_REPORTS: "roro"
  #   container_name: ci

  # guard:
  #   <<: *test
  #   command: bundle exec guard
  #   container_name: guard

  # production: &production
  #   extends:
  #     file: docker-compose.builders.yml
  #     service: roro-production
  #   volumes:
  #     - .:/usr/src
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - gem_cache:/usr/local/bundle/gems

  # roro:
  #   <<: *production
  #   volumes:
  #     - .:/artifact
  #   image: handsomefencer/roro
  #   command: ['sh']

volumes:
  gem_cache:  