services:
  development: &development 
    build:
      dockerfile: mise/containers/roro/Dockerfile.development
      tags: 
        - handsomefencer/roro:development
    image: handsomefencer/roro
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
      - gem_cache:/usr/local/bundle/gems

  dev: 
    <<: *development

  # test: &test
  #   command: bundle exec rake test
  #   <<: *development

  # test-all: 
  #   <<: *test
  #   environment: 
  #     DEBUGGERER: true

  # guard:
  #   <<: *test
  #   command: bundle exec guard