services:
  production: &production
    build:
      dockerfile: mise/containers/roro/Dockerfile.production
      tags: 
        - handsomefencer/roro:production
    depends_on: 
      - builder
    image: handsomefencer/roro
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
      - gem_cache:/usr/local/bundle/gems

  roro:
    <<: *production
    command: ['sh']

