x-base: &base
  build:
    args: 
      RUBY_VERSION: 3.3
    dockerfile: ./mise/containers/roro/Dockerfile.builder.ruby
  profiles: 
    - builder
  volumes:
    - gem_cache:/usr/local/bundle/gems

services:
  builder-ruby:
    <<: *base
    image: builder/ruby

  builder-base:
    <<: *base
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.builder.base
    depends_on: 
      - builder-ruby
    image: builder/base

  builder-development: 
    <<: *base
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.development
    depends_on: 
      - builder-base
    image: builder/development

  builder-test: 
    <<: *base
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.test
    depends_on: 
      - builder-cache
    image: builder/test

  builder-production:
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.production
    image: builder/production
    depends_on: 
      - builder-base
    profiles: 
      - builder  

