x-base: &base
  build:
    args: 
      RUBY_VERSION: 3.3
    dockerfile: ./mise/containers/roro/Dockerfile.builder.ruby
  profiles: 
    - builder
  volumes:
    - .:/usr/src
    - gem_cache:/usr/local/bundle/gems

services:
  roro-ruby:
    <<: *base
    image: roro/ruby

  roro-base:
    <<: *base
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.builder.base
    depends_on: 
      - roro-ruby
    image: roro/base

  roro-development: 
    <<: *base
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.development
    depends_on: 
      - roro-base
    image: roro/development

  roro-production:
    build:
      dockerfile: ./mise/containers/roro/Dockerfile.production
    image: roro/production
    depends_on: 
      - roro-base
    profiles: 
      - builder  

