FROM ruby:<%= config[:ruby_version] %>


RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y build-essential git nodejs yarn


ENV APP_HOME /usr/src/app/
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY Gemfile* $APP_HOME 

ENV BUNDLE_PATH /gems

RUN bundle install
RUN yarn 

COPY . ./$APP_HOME



