FROM ruby:<%= @env[:base][:ruby_version][:value] %>-alpine AS builder

RUN apk add --update \
  build-base \
  <%= @env[:base][:alpine_db_pkg][:value] %>

RUN apk add --update\
  file \
  git \
  nodejs \
  tzdata \
  yarn

RUN gem install bundler:<%= @env[:base][:bundler_version][:value] %>

WORKDIR /app

## Install standard gems
COPY Gemfile Gemfile.lock ./
RUN bundle install -j4 --retry 3

RUN yarn install

COPY . ./

RUN bundle install

CMD ["./entrypoints/docker-entrypoint.sh"]