ARG RUBY_IMAGE=ruby:<%= config['ruby_version'] %>-alpine
FROM $RUBY_IMAGE

RUN apk add --no-cache --update build-base linux-headers git

WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN gem install bundler
RUN bundle 
RUN bundle exec rake install
RUN bundle exec rake test
