---
jobs:
- build
- test:
    requires: 
      - build
    filters:
      branches:
        only:
        - main
    matrix:
      parameters:
          regex:
              - '**/postgres/**/7_0/**/*'
              - '**/postgres/**/6_1/**/*'
              - '**/mysql/**/7_0/**/*'
              - '**/mariadb/**/7_0/**/*'
              - 'ruby/omakase/'