---
jobs:
- test-rubies:
    filters:
      branches:
        only: main
    matrix:
      parameters:
        version:
        - '3.1'
        - '3.2'
        - '3.3'
        folder:
        - cli
        - common
        - configurators
        - crypto
