---
jobs:
- build
- test-stacks:
    requires: 
      - build
    filters:
      branches:
        only:
        - development
        - stack-test-vcr
- test-roro:
    requires: 
      - build
    filters:
      branches:
        only:
        - development
       