# syntax=docker/dockerfile:1
FROM handsomefencer/roro/builder AS builder

FROM builder

COPY . .

COPY --from=builder /usr/local/bundle /usr/local/bundle

RUN bundle

# RUN gem build roro.gemspec

# RUN rake install


