# syntax=docker/dockerfile:1

FROM builder/base AS builder

FROM builder

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /usr/src/Gemfile* ./

RUN bundle

COPY . .

RUN gem build roro.gemspec
RUN rake install