# syntax=docker/dockerfile:1

FROM roro/base AS builder

FROM builder

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /usr/src/Gemfile* ./

COPY . .

RUN bundle update --bundler \   
  && bundle


RUN gem build roro.gemspec
RUN bundle install && bundle exec rake install
