executor: machine-ubuntu
steps:
  - checkout
  - run: docker-compose build --with-dependencies test
  - run: docker-compose build test
  - run: docker-compose run --rm test bundle
  - run: docker-compose build test

