executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run: docker-compose build --with-dependencies development
  # - run: docker-compose build test
  - run: 
      command: |
        cat .circleci/splits/testfiles_roro.txt | circleci tests split > /tmp/tests-to-run
        export TESTFILES=$(cat /tmp/tests-to-run)
        docker compose run --rm -e TESTFILES="$TESTFILES" test bundle exec rake test:ci
      # command: |
      #   circleci tests split .circleci/splits/testfiles_roro.txt --split-by=timings)" \
      #   && docker compose run --rm -e TESTFILES="$TESTFILES" test bundle exec rake test:ci

      # command: |
      #   export TEST_FILES="$(circleci tests split .circleci/splits/testfiles_roro.txt --split-by=timings)" \
      #   && docker compose run --rm -e TESTFILES="$TESTFILES" test bundle exec rake test:ci
      when: always
  - store_test_results:
      path: ~/project/test/reports
  - store_artifacts:
      path: ~/project/test/reports    
