executor: machine-ubuntu

steps:
  - checkout
  - run: docker-compose build --with-dependencies test
  - run: docker-compose build test
  ## does this create an image?
  - run: docker-compose run --rm test bundle
  - run: 
      command: |
          export TESTFILES=$(cat .circleci/splits/testfiles_roro.txt)
          docker compose run --rm -e TESTFILES="$TESTFILES" -e CI="true" test bundle exec rake test:ci
      when: always
  - store_test_results:
      path: test/reports

  - store_artifacts:
      path: test/reports

