executor: machine-ubuntu
steps:
  - checkout
  - run: 
      command: |
          docker-compose build --with-dependencies test
          docker-compose run --rm test bundle
          docker-compose build test
          export TESTFILES=$(cat .circleci/splits/testfiles_roro.txt)
          docker compose run --rm -e TESTFILES="$TESTFILES" test bundle && bundle exec rake test:ci
      when: always
  - store_test_results:
      path: ~/project/test/reports
  - store_artifacts:
      path: ~/project/test/reports    
