
executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run:
      command: |
        docker compose build --with-dependencies test \
        && docker compose run --rm test bundle \
        && circleci tests glob "test/roro/cli/**/*_test.rb" | circleci tests split > /tmp/tests-to-run \
        && docker compose run --rm test bundle exec rake test $(cat /tmp/tests-to-run)
        
      when: always
  - store_test_results:
      path: ~/project/test/reports
  - store_artifacts:
      path: ~/project/test/reports
