parameters:
  regex:
    description: regex for test file subsection
    default: '**/*'
    type: string
executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - restore-and-save-cache
  - run:
      command: |
        export DEBUGGERER='true'
        bundle exec rake test:roro
      when: always
  - store_test_results:
      path: test/reports
