executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - restore-and-save-cache
  - run: 
      command: |
        TEST_FILES="$(circleci tests split .circleci/splits/testfiles_roro.txt --split-by=timings)"
        bundle exec rails test $TEST_FILES            
      when: always
  - store_test_results:
      path: ~/project/test/reports
  - store_artifacts:
      path: ~/project/test/reports    
