executor: machine-ubuntu

steps:
  - checkout
  - run: 
      command: |
          export TESTFILES=$(cat .circleci/splits/testfiles_roro.txt)
          docker compose run --rm -e TESTFILES="$TESTFILES" -e CIRCLE_TEST_REPORTS="roro" test-ci
      when: always
  - store_test_results:
      path: test/reports/roro
  - store_artifacts:
      path: test/reports/roro


