
executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run: docker-compose run --rm test bundle
  - run:
      command: |
        export TESTFILES=$(cat .circleci/splits/testfiles_stacks.txt | circleci tests split --split-by=timings)
        docker compose run --rm -e TESTFILES="$TESTFILES" -e CIRCLE_TEST_REPORTS="stacks" test-ci
      when: always
  - store_test_results:
      path: test/reports/stacks

  - store_artifacts:
      path: test/reports/stacks
