executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run: bundle
  - run:
      command: |
        cat .circleci/splits/testfiles_roro.txt | circleci tests run --command="xargs bundle exec rake test" --verbose --split-by=timings
  - store_test_results:
      path: ~/project/test/reports
  - store_artifacts:
      path: ~/project/test/reports    
