parameters:
  regex:
    description: regex for test file subsection
    default: '**/*'
    type: string
executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run:
      command: |
        docker compose build --with-dependencies test
        docker compose run --rm test bundle
        docker compose run --rm test bundle exec rake test:roro
  - store_test_results:
      path: test/reports