
executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run:
      command: |
        docker compose build --with-dependencies test \
        && docker compose run --rm test bundle \
        && docker compose run --rm test bundle exec rake test:roro
      when: always
  - store_test_results:
      path: ~/project/test/reports
  - store_artifacts:
      path: ~/project/test/reports
