executor: machine-ubuntu
parallelism: 5
steps:
  - checkout
  - run:
      command: |
        docker compose build --with-dependencies test \
        && docker compose run --rm test bundle \
        && circleci tests glob "test/roro/cli/**/*_test.rb" | circleci tests split --split-by=timings > /tmp/tests-to-run \
        && docker compose run --rm test bundle exec rake test $(cat /tmp/tests-to-run)
  - store_test_results:
      path: test/reports