FROM ruby:<%= @env[:base][:ruby_version][:value] %>-alpine


RUN gem install bundler:<%= @env[:base][:bundler_version][:value] %>

WORKDIR /app

## Install standard gems
COPY Gemfile Gemfile.lock ./
RUN bundle install -j4 --retry 3

RUN yarn install

COPY . ./

RUN bundle install
RUN chmod -R 755 ./entrypoints/docker-entrypoint.sh

CMD ["./entrypoints/docker-entrypoint.sh"]