FROM ruby:<%= @env[:base][:ruby_version][:value] %>-alpine
  
## Install standard gems
COPY Gemfile Gemfile.lock ./
RUN bundle install -j4 --retry 3

RUN yarn install

RUN chmod -R 755 ./entrypoints/docker-entrypoint.sh

CMD ["./entrypoints/docker-entrypoint.sh"]