FROM ruby:<%= @env[:base][:ruby_version][:value] %>-alpine AS builder

RUN apk add --update --no-cache \
  binutils-gold \
  build-base \
  curl \
  file \
  g++ \
  gcc \
  git \
  less \
  libstdc++ \
  libffi-dev \
  libc-dev \
  linux-headers \
  libxml2-dev \
  libxslt-dev \
  libgcrypt-dev \
  make \
  netcat-openbsd \
  nodejs \
  openssl \
  pkgconfig \
  postgresql-dev \
  tzdata \
  nodejs \
  yarn

WORKDIR /app

# install yarn
RUN yarn install --check-files

# Install standard gems
COPY Gemfile* /app/
RUN gem install bundler:<%= @env[:base][:bundler_version][:value] %>
RUN bundle install -j4 --retry 3

COPY . ./app/

RUN bundle exec rake webpacker:compile

CMD ["./entrypoints/docker-entrypoint.sh"]