# syntax=docker/dockerfile:1

FROM composer as builder
  
WORKDIR /app/

RUN composer create-project laravel/laravel \
  <%= @env[:base][:app_name][:value]%>

FROM scratch AS export-stage

COPY --from=builder ./app/<%= @env[:base][:app_name][:value]%> .