# syntax=docker/dockerfile:1

FROM composer:2.0 as builder

WORKDIR /app

COPY database/ database/
COPY composer.json composer.json
COPY composer.lock composer.lock

RUN composer install \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --no-dev \
    --prefer-dist

COPY . .

RUN composer create-project laravel/laravel <%= @env[:base][:app_name][:value] 
%> 4.2 --prefer-dist


FROM scratch AS export-stage

COPY --from=builder ./app/ .

RUN composer dump-autoload