require_relative 'rollon_as_quickstart.rb'
require_relative 'rollon_as_roro.rb'
require_relative 'database/with_postgres.rb'
require_relative 'database/with_mysql.rb'
require_relative 'database/database.rb'