# syntax=docker/dockerfile:1
FROM ruby:3.0-alpine

RUN apk add \
    build-base \
    file \
    git \
    docker \
    docker-compose \
    sudo

WORKDIR /usr/src

RUN gem install bundler:2.2.32

COPY . .

RUN bundle
RUN rake install

WORKDIR /home/schadenfred