# syntax=docker/dockerfile:1
FROM ruby:3.0-alpine AS builder

RUN apk add \
    build-base \
    file \
    git \
    docker \
    docker-compose \
    sudo

RUN gem install bundler:2.2.32
RUN apt-get install -y docker docker-compose sudo

WORKDIR /usr/src

COPY . .

RUN bundle
RUN rake install

WORKDIR /home/schadenfred