# syntax=docker/dockerfile:1

FROM ruby:<%= @env[:base][:ruby_version][:value] %>-alpine

ARG UID=1000
ARG GID=1000

USER ${UID}:${GID}

<%= section('packages') %>

WORKDIR /app

RUN gem install bundler:<%= @env[:base][:bundler_version][:value] %>

COPY Gemfile Gemfile.lock ./
RUN bundle install -j4 --retry 3

COPY --chown=${UID}:${GID} . .

RUN bundle install   -j4 --retry 3

RUN chmod -R 755 entrypoints/docker-entrypoint.sh

RUN yarn install

CMD ["./entrypoints/docker-entrypoint.sh"]