# syntax=docker/dockerfile:1

FROM builder/cache AS cache
FROM builder/dependencies AS Development

COPY  \
  --from=cache \
  /usr/local/bundle /usr/local/bundle

# COPY  \
#   --from=cache \
#   /app/node_modules /app/node_modules

# COPY package.json yarn.lock ./

# RUN yarn install 

COPY Gemfile* ./

RUN bundle

COPY . .