# syntax=docker/dockerfile:1

FROM builder/base

RUN apk add --update --no-cache \
  build-base \
  git

RUN apk add --update --no-cache \
  gcompat \
  libc6-compat \
  glib-dev \
  musl

<%= section('dockerfile/development/packages') %>