# syntax=docker/dockerfile:1

FROM builder/base

RUN apk add --update --no-cache \
  build-base \
  sqlite-dev \
  # nodejs \
  # postgresql-dev \
  # yarn \ 
  && apk cache -v sync

# RUN apk add --update --no-cache \
#   && apk cache -v sync

  
