# syntax=docker/dockerfile:1

FROM ruby:<%= @env.dig(:base, :ruby_version, :value) %>-alpine<%= @env.dig(:base, :alpine_version, :value) %> 

RUN gem update --system \
  && gem cleanup \
  && bundle config jobs 4 \
  && bundle config retry 4

RUN apk add --update --no-cache \ 
  tzdata \
  && apk cache -v sync

WORKDIR /app
