# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.3.1
    
FROM ruby:${RUBY_VERSION}-alpine<%= @env.dig(:base, :alpine_version, :value) %> 

RUN gem update --system \
  && gem cleanup \
  && bundle config jobs 4 \
  && bundle config retry 4

RUN apk add --update --no-cache \ 
  tzdata \
  && apk cache -v sync

WORKDIR /app
