# syntax=docker/dockerfile:1

FROM builder/cache AS Cache
FROM builder/deps-dev AS Test

RUN apk add --update --no-cache \
  chromium-chromedriver \
  && apk cache -v sync

<%= section('dockerfile/development/cache/from') %>

COPY . .