# syntax=docker/dockerfile:1

FROM builder/dependencies AS generator

RUN echo -e "source 'https://rubygems.org'\ngem 'rails', '~> <%= @env[:base][:rails_version][:value] %>'" > Gemfile

RUN bundle

RUN bundle exec rails new . \
<%= section('rails_new_sections') %>
RUN rm config/master.key

FROM scratch AS export-stage

COPY --from=generator ./app/ .


  