# syntax=docker/dockerfile:1

FROM builder/cache AS Cache
FROM builder/dependencies AS Test

RUN apk add --update --no-cache \
  chromium-chromedriver \
  && apk cache -v sync

<%= section('dockerfile/steps/cache/from') %>

COPY . .