# syntax=docker/dockerfile:1

FROM python:<%= @env[:base][:python_version][:value] %>
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
RUN pip install -r requirements.txt
COPY . /code/