# syntax=docker/dockerfile:1

FROM python:<%= @env[:base][:python_version][:value] %>

# establish the working directory 
WORKDIR /code

# copy and install requirements.txt to speed up caching:
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .