# syntax=docker/dockerfile:1

FROM python:<%= @env[:base][:python_version][:value] %> AS builder
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code

RUN python -m pip install flask redis

COPY . /code/

RUN pip freeze > requirements.txt

FROM scratch AS export-stage

COPY --from=builder ./code/ .